server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
logging:
  config: classpath:logback-spring.xml

line:
  api-domain: https://api.line.me/v2
  login:
    channel-id: 1656789218
    channel-secret: ENC(NkEKgLR5i0p4BLrW2wCiU+GXw3OMPf2kbFn3OeruiQWPCb+hPrrHn0POlW9/DoPUpEpcfB2/TsI=)
  message:
    self-uid: U418d31259be6c881f451e9e6cbfb2045
    channel-id: 1656324239
    channel-secret: ENC(Nhq/EYNtu5u9mefCqqJUL80qHuxBDOabfS9JqvRmn6caxidvRF08ZavUVSl2sIUPPYufvEpyTEM=)
    channel-token: ENC(lxn6WeK+PE3/3gHf1Cn7HwwEnZ3+pEaYSgAXsP9d7+V31BAZYifzdW118l2ky5ihsIBb0+/zE7SbKDrrRY99n7MmjxzkGMQKbEd0P0tAy27jtZcmd616FF7ShKjyCg2DCSkeXSKlR+ubOfnNmo6JS2zTd9+i0186zH9rxRBfTsw5PBAeWOhZ/7U2/FD70YBFr/duLzb19EZf9Zh1PFJOR1ehvFr22BoytNRvLAaV1wuT7jx8FpaVmIyhit0tEMfh)
  notify:
    api-domain: https://notify-api.line.me
    self-token: ENC(7BGyYLbr6mVUCqKWT23S4HGSFMec3IwsacUtFXxlzq6dxn3mV7h4iO0qALmWszxeGLmFyiqXEtwUfjUocG8Eng==)
