spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(kXOCZnrnuYR8imQuBCKygbD9ltnQeS2RKWnK18X0KwlthntIqKX/x1YLhYXHwhH7MuJKg6kRpElpRekUlmkFASfLeZiLft1hkVgWaVcomxesCqvaIiq7ZdgtfkGErF7t0js0bTY8vqSxwU04gLfzjLz39a2o81e/zdds8CdIR0gMD4GZ01illlkA0DOX7O52k3eFjTgKgJx/zmc3PrZaIMOdpA8lQLOCdn0YVcaKETA=)
    username: ENC(7+G7M9ghLZhhvvWjBY3x6HkXBOZ24F4btKi/vOZjid8=)
    password: ENC(BI/xcH2NcCBYakJapCYiG8ADcAIAJ7Xe)
    hikari:
      idle-timeout: 120000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: true