server:
  port: 8080
  servlet:
    context-path: /TangDong
spring:
  thymeleaf:
    mode: HTML
  config:
    import: line-config.yml
  profiles:
    active: dev
  messages:
    basename: i18n/messages
logging:
  config: classpath:logback-spring.xml

