spring:
  ai:
    openai:
      api-key: ENC(SkoevxLe9vAxfGecJzhDSHYRbG0URh1hM9L+Fmu3EnGUjFBZXEtLv3Fsd4haxThOW2m38H54DpeR2uM3LsavpJeKly5f7fNuphSV0BpNS6Q=)
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-70b-versatile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(NCLuQLAmaVNntetMxUYuiDkjcHdOnRpMY1WO1HKnsminRNATLuFWR9MPZg2nnFPofsaLF+14gJzTk3moOMCdpOtrpmea+UXe90GgSTgpbyQ9IofMM6WQJwmtkFkyRGnhDHvbT1jJGZMf10Y7uhyb5sDtKtBb4IzWe/5kB9Yc6d8c+8E9q2pUG3xh8Ry/OU8OLxpRxqtqHEET/QRlUlasyg==)
    username: ENC(7+G7M9ghLZhhvvWjBY3x6HkXBOZ24F4btKi/vOZjid8=)
    password: ENC(BI/xcH2NcCBYakJapCYiG8ADcAIAJ7Xe)
    hikari:
      idle-timeout: 120000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: true
  data:
    redis:
      database: 1
      host: ENC(HNI18PJ4ZE+VXrIhqqLK7C8+lk45jhAn3uodY209tfE=)
      port: ENC(7yvqJMAkinGQ4ZTTscepHA8Zc/4KwCMG)
      password: ENC(Pmmt1JumUhyWkQ4lsRVDOJxdJtnrcOKo)
      timeout: 10s
      lettuce:
        pool:
          # 連線池最大連線數 預設:8 (負數表示沒有限制)
          max-active: 8
          # 連線池最大阻塞等待時間 (使用負值表示沒有限制) 預設:-1
          max-wait: -1
          # 連線池中的最大空閒連線 預設:8
          max-idle: 8
          # 連線池中的最小空閒連線 預設:0
          min-idle: 0
  cache:
    enabled: false
    # 快取類型 redis、none (不使用快取)
    type: redis
    # 快取時間 (單位:ms)
    redis:
      time-to-live: 3600000
      # 快取null值，防止快取穿透
      cache-null-values: true