line:
  header:
    signature: x-line-signature
    request-id: x-line-request-id
  api-domain: https://api.line.me/v2
  api-data-domain: https://api-data.line.me/v2
  login:
    channel-id: ENC(gTTUHkjCwHfTIjTM1oHTJPLtS2kcTmKzPI4Gsjpcphk=)
    channel-secret: ENC(taGyrEW1LFQy9NkrkE0P7ISsJojjgU31Mt55uIdu72tywJU07vSrBGjhZkn6EMdZwCrx/jXuU/U=)
  message:
    self-uid: U2c4b24b25fe4de46a9875a2c83c94063
    channel-id: ENC(MYz7sKMrVagGaO7m7jkKIC0qR5Z5qyKpEOzJD+nYEGE=)
    channel-secret: ENC(6Ky5Ls9l1QbhigcKp7LUV4Jj4pLVnGLGTl/1r5mNR5dMkKvLfRTMsTHTi2O2XtrwUKmK4BT1AEg=)
    channel-token: ENC(L9WHvqmHfcv1hm6eqPqyAMnIckuwrqF7bIn+/7aWblBPDkZRfvth3PEsasdLFa7MonOfUmUZ0tl8QFLod+bUd4PBvDj1edhK3zuI4OhwLEFzpxcsNqU2p50eA6oYne6Sp9R4sTvOnJjbNlVRDu4xmh6KJJq1vX0y0eZfe26xumeTF4lpqlu+gbCNtRkKVDgslkhAGZTejSh+gHMscFQE8fFkaapaKua8QTXK1rJyiEu+wepeYLte3/z9NdZNDGgR)
  notify:
    client-id: Vpk9dSKkUorPf5IGgf751K
    client-secret: M8HXMmicoDRl92jAE0bJCDlUvI7gLOnhPilzP6LcALo
    api-domain: https://notify-api.line.me
    oauth-domain: https://notify-bot.line.me
    central-control-group-token: 8GVaqQS4AcIrSccW3qfNuWbqFpZ53DqDTQGeWOnEltO
    self-token: ENC(7BGyYLbr6mVUCqKWT23S4HGSFMec3IwsacUtFXxlzq6dxn3mV7h4iO0qALmWszxeGLmFyiqXEtwUfjUocG8Eng==)
    callback-domain: https://b0a4-1-34-8-160.ngrok-free.app
